export const spanClassMap: Record<number, string> = {
  12: 'col-span-12',
  11: 'col-span-11',
  10: 'col-span-10',
  9: 'col-span-9',
  8: 'col-span-8',
  7: 'col-span-7',
  6: 'col-span-6',
  5: 'col-span-5',
  4: 'col-span-4',
  3: 'col-span-3',
  2: 'col-span-2',
  1: 'col-span-1',
};
export const smSpanClassMap: Record<number, string> = {
  12: 'sm:col-span-12',
  11: 'sm:col-span-11',
  10: 'sm:col-span-10',
  9: 'sm:col-span-9',
  8: 'sm:col-span-8',
  7: 'sm:col-span-7',
  6: 'sm:col-span-6',
  5: 'sm:col-span-5',
  4: 'sm:col-span-4',
  3: 'sm:col-span-3',
  2: 'sm:col-span-2',
  1: 'sm:col-span-1',
};
export const mdSpanClassMap: Record<number, string> = {
  12: 'md:col-span-12',
  11: 'md:col-span-11',
  10: 'md:col-span-10',
  9: 'md:col-span-9',
  8: 'md:col-span-8',
  7: 'md:col-span-7',
  6: 'md:col-span-6',
  5: 'md:col-span-5',
  4: 'md:col-span-4',
  3: 'md:col-span-3',
  2: 'md:col-span-2',
  1: 'md:col-span-1',
};
export const lgSpanClassMap: Record<number, string> = {
  12: 'lg:col-span-12',
  11: 'lg:col-span-11',
  10: 'lg:col-span-10',
  9: 'lg:col-span-9',
  8: 'lg:col-span-8',
  7: 'lg:col-span-7',
  6: 'lg:col-span-6',
  5: 'lg:col-span-5',
  4: 'lg:col-span-4',
  3: 'lg:col-span-3',
  2: 'lg:col-span-2',
  1: 'lg:col-span-1',
};
export const xlSpanClassMap: Record<number, string> = {
  12: 'xl:col-span-12',
  11: 'xl:col-span-11',
  10: 'xl:col-span-10',
  9: 'xl:col-span-9',
  8: 'xl:col-span-8',
  7: 'xl:col-span-7',
  6: 'xl:col-span-6',
  5: 'xl:col-span-5',
  4: 'xl:col-span-4',
  3: 'xl:col-span-3',
  2: 'xl:col-span-2',
  1: 'xl:col-span-1',
};
export const xxlSpanClassMap: Record<number, string> = {
  12: '2xl:col-span-12',
  11: '2xl:col-span-11',
  10: '2xl:col-span-10',
  9: '2xl:col-span-9',
  8: '2xl:col-span-8',
  7: '2xl:col-span-7',
  6: '2xl:col-span-6',
  5: '2xl:col-span-5',
  4: '2xl:col-span-4',
  3: '2xl:col-span-3',
  2: '2xl:col-span-2',
  1: '2xl:col-span-1',
};

export const spanClassMaps = {
  default: spanClassMap,
  sm: smSpanClassMap,
  md: mdSpanClassMap,
  lg: lgSpanClassMap,
  xl: xlSpanClassMap,
  xxl: xxlSpanClassMap,
};
